package:
  name: llvmlite
  # GIT_DESCRIBE_TAG may not be set
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..
  #git_url: https://github.com/numba/llvmlite.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python 3.8*
    # On channel https://anaconda.org/numba/
    - llvmdev 3.7*
    - enum34         [py27]
  run:
    - python 3.8*
    - enum34         [py27]

test:
  imports:
    - llvmlite
    - llvmlite.binding

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
